/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.TD2;

public class App {

    public static void main(String[] args) throws InterruptedException {

        String T1 = "Souvent, pour s’amuser, les hommes d’équipage";
        String T2 = "Prennent des goélands, vastes oiseaux des mers,";
        String T3 = "Qui suivent, indolents compagnons de voyage,";
        String T4 = "Le navire glissant sur les gouffres amers.";

        Monotache t1 = new Monotache(T1);
        Monotache t2 = new Monotache(T2);
        Monotache t3 = new Monotache(T3);
        Monotache t4 = new Monotache(T4);

        t1.start();
        t1.sleep(5);
        //t1.join();
        t2.start();
        t2.sleep(5);
        //t2.join();
        t3.start();
        t3.sleep(5);
        //t3.join();
        t4.start();
        t4.sleep(5);
        //t4.join();
    }
}