/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.TD2;

import main.java.TD2.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
}
