/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        //System.out.println(new App().getGreeting());
        MonThread t1= new MonThread();
        MonThread t2= new MonThread();
        t1.start();
        t2.start();

        /*t1.inc();
        System.out.println("T1 inc");
        t2.inc();
        System.out.println("T2 inc");
        t1.dec();
        System.out.println("T1 dec");
        t2.dec();
        System.out.println("T2 dec");*/


    }
}
